---
app_name: XJZProxy
app_version: 0.1.6
ruby_version: <%= File.read('./.ruby-version') %>
packages_dir: <%= File.join(Dir.home, 'Documents/Ruby-Binary') %>
online_verify_url: https://l.xjz.pw/v

# build package
icon_path: <%= File.expand_path('../releases/icon.png', __FILE__) %>
