#! /usr/bin/env ruby
#
require 'optparse'
require_relative './xjz_license'

options = {}
parser = OptionParser.new do |opts|
  opts.banner = "Usage: manager [options]"

  opts.on(
    '-gLICENSE_PATH', '--generate LICENSE_PATH',
    'Generate a license and write to the file'
  ) do |path|
    options[:g] = path
  end

  opts.on('--id STRING', 'license owner user id') do |id|
    options[:id] = id
  end

  opts.on('-fFLAG', '--flag FLAG', 'license flags, split by "," or use multiple times') do |f|
    options[:flags] ||= []

    if Array === f
      options[:flags].push(*f)
    else
      options[:flags] << f.to_s
    end
  end

  opts.on('-cLICENSE_PATH', '--check LICENSE_PATH', 'Check license') do |path|
    options[:c] = path
  end
end
parser.parse!

if options.empty?
  puts parser.help
  exit 1
end

manager = XJZLicense.new(File.expand_path('../license_key', __FILE__))

if path = options[:g]
  if File.exist?(path)
    $stderr.puts "File #{path} existed"
    exit 1
  elsif options[:id] && options[:flags]
    l = manager.generate_license(options[:id], options[:flags])
    File.write(path, l)
  else
    $stderr.puts "id and flags is required"
    exit 1
  end
end
