#! /usr/bin/env ruby

ENV['RACK_ENV'] = 'production'

require 'rack'

require 'bundler'
Bundler.require(:default, :license_server)

require_relative './license_server'

Rack::Handler::WEBrick.run LicenseServer.new
