---
project:
  host: xjz\.pw
  desc: desc
plugins:
- title: auth token
  labels:
  - auth
  - l1
  template:
    params:
      token: ".t/string"
- title: script
  labels:
  - l1
  script: ".f/test.rb"
- title: l1 plug
  labels:
  - l1
  - l2
  template:
    response:
      err:
        http_code: 400
        data:
          code: 1
          msg: err
