---
project:
  url: https://xjz.pw
  desc: desc
plugins:
  auth:
    filter:
      include_labels:
      - all
      exclude_labels:
      - no_auth
      path: "/api/v1"
      methods:
      - GET
      - POST
    query: 
    body: 
    params:
      token: ".t/string"
      ".token.required": true
    headers: 
  other:
    filter:
      include_labels:
      - all
      path: "/api/v1"
    script: ".f/test.rb"
