---
root_ca_path: config/root_ca.pem
key_path: config/key.pem
proxy_timeout: 60  # seconds
proxy_port: 9898
proxy_http2: false
max_threads: 32
logger_level:
  default: debug

projects:
  - ../xjzapidoc
