---

default: &default
  root_ca_path: config/root_ca.pem
  key_path: config/key.pem
  proxy_timeout: 60 # seconds
  proxy_port: 9898
  alpn_protocols:
    - h2
    - http/1.1
  max_threads: 64
  logger_level:
    default: info

  # template_dir: /path/to/templates

  # .api_projects will auto generate by projects
  projects:

  # proxy_mode: all # proxy any host
  proxy_mode: whitelist # proxy projects and filter by rules

  host_whitelist:
    - xjz.pw # proxy host with prefix +

  webview_debug: true

prod:
  <<: *default
  max_threads: 128

  logger_level:
    default: debug

  host_whitelist: []

dev:
  <<: *default
  logger_level:
    default: debug
    io_helper.rb: info

  proxy_mode: all

  projects:
    - ../xjzapidoc_examples/example1.yml
    - ../xjzapidoc_examples/example2
    - ../xjzapidoc_examples/example3

test:
  <<: *default
  root_ca_path: tmp/root_ca.pem
  key_path: tmp/key.pem
  proxy_timeout: 1
  proxy_port: 59898
  max_threads: 4
  projects:
    - ./spec/files/project.yml

  proxy_mode: whitelist
  host_whitelist: [ xjz.com ]

  template_dir: ./spec/files/webviews

  logger_level:
    default: debug
    io: info
