---

default: &default
  root_ca_path: config/root_ca.pem
  key_path: config/key.pem
  proxy_timeout: 60 # seconds
  proxy_port: 9898
  alpn_protocols:
    # - h2
    - http/1.1
  max_threads: 128
  logger_level:
    default: info

  # template_dir: /path/to/templates

  # .api_projects will auto generate by projects
  projects:

  # auto add project when put a project to this folder
  projects_dir: <%= File.join(Dir.home, 'XJZProxy') %>

  # proxy_mode: all # proxy any host
  proxy_mode: whitelist # proxy projects and filter by rules

  host_whitelist:
    - xjzasdf.pw # proxy host with prefix +

  license_path:

  webview_debug: false
  ui_window: true

prod:
  <<: *default

  logger_level:
    default: warn

  host_whitelist: []

dev:
  <<: *default
  logger_level:
    default: debug
    io_helper.rb: info

  proxy_mode: all

  webview_debug: true
  ui_window: true

test:
  <<: *default
  root_ca_path: tmp/root_ca.pem
  key_path: tmp/key.pem
  proxy_timeout: 1
  proxy_port: 59898
  max_threads: 4

  alpn_protocols:
    - h2
    - http/1.1

  projects:
    - ./spec/files/project.yml
  projects_dir: <%= File.join($root, 'tmp/projects_dir_test') %>

  proxy_mode: whitelist
  host_whitelist: [ xjz.com ]

  template_dir: ./spec/files/webviews

  logger_level:
    default: debug
    io: info

  webview_debug: false
  ui_window: true
