---
root_ca_path: tmp/root_ca.pem
key_path: tmp/key.pem
proxy_timeout: 1
proxy_port: 59898
max_threads: 8
alpn_protocols:
  - h2
  - http/1.1
logger_level:
  default: debug
projects:
  - ./spec/files/project.yml
