#! /usr/bin/env bash

set -ex

root="$(pwd)"

if [[ ! -f lib/webview/webview || $FORCE_BUILD ]]; then
  # build webview
  go get github.com/zserge/webview
  cd lib/webview
  # output lib/webview/webview
  rm -f ./webview
  go build
fi
