#! /usr/bin/env bash

set -ex

root="$(pwd)"

if [[ ! -f ext/webview/webview || $FORCE_BUILD ]]; then
  # build webview
  go get github.com/zserge/webview
  cd ext/webview
  # output ext/webview/webview
  rm -f ./webview
  go build
fi
