#! /bin/bash

set -e

SELFDIR="`dirname \"$0\"`"
SELFDIR="`cd \"$SELFDIR\" && pwd`"

export BUNDLE_GEMFILE="$SELFDIR/lib/app/Gemfile"
unset BUNDLE_IGNORE_CONFIG

exec "$SELFDIR/lib/ruby/bin/ruby" "$SELFDIR/lib/app/boot"
